# Generated by Django 5.0.5 on 2024-05-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
